### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by deaale6** [andreagemelli/doc2graph#14]
![Screenshot 2023-09-25 alle 18 37 48 (2)](https://github.com/andreagemelli/doc2graph/assets/105798974/a4919a99-0fd1-486f-b94e-bf3443d3b68c)

How can I fix this error? I have a 23GB of GPU.

**Comment by andreagemelli** [comment]
Hi @deaale6 ,
Did you try to use kNN connection instead of fully-connected?
You can do this following the instruction on the README.md file.
Let me know,
A.
