### ISSUE TITLE
Facing some Issue when i try to run main.py

### ISSUE THREAD

**Issue by NaveenVinayakS** [andreagemelli/doc2graph#2]
![image](https://user-images.githubusercontent.com/27666222/206603180-83717255-8908-4d29-a1ac-a0b3efec7d43.png)

**Comment by andreagemelli** [comment]
Dear Naveen,
I think the problem is with the file format.
For some reasons we used jpg instead of png during training.
I will fix the code asap, in the meantime you can adjust it by yourself checking the "jpg" lines directly in the code or the file format.

**Comment by NaveenVinayakS** [comment]
Thank you.. it fixed my issue
