### ISSUE TITLE
RunTime error:  float division by zero in main.py

### ISSUE THREAD

**Issue by NaveenVinayakS** [andreagemelli/doc2graph#3]
![image](https://user-images.githubusercontent.com/27666222/206940246-29e2c934-0561-4447-8766-c3902fbb5049.png)

when i run python main.py i am facing the above issue.Kindly help me in this

**Comment by NaveenVinayakS** [comment]
This issue is solved when i did some changes in preprocessing.yaml ,by enabling  one of the feature to TRUE.

**Comment by andreagemelli** [comment]
Maybe it is better for other users report which feature as well.

**Comment by NaveenVinayakS** [comment]
This is the changes that i have made in preprocessing.yaml
![image](https://user-images.githubusercontent.com/27666222/207259843-ba363863-66de-4b92-ba34-9e36a568a3d5.png)

where i have set "add_embs:True"

**Comment by andreagemelli** [comment]
By the way, these changes are made automatically using the settings from the command line (preprocessing.yaml is edited at run time).
I will fix the bug about division when not using embeddings, thanks.

**Comment by NaveenVinayakS** [comment]
Hi @andreagemelli  can help  me in solving issue #4
