### ISSUE TITLE
python src/main.py giving KeyError: 'feat'

### ISSUE THREAD

**Issue by NaveenVinayakS** [andreagemelli/doc2graph#4]
![image](https://user-images.githubusercontent.com/27666222/207232908-85d8a71f-3e3d-4c82-b43c-a72feed04693.png)

**Comment by andreagemelli** [comment]
You are not probably loading features on edges "add_eweights=True".
I'll handle this behaviour as well.

**Comment by NaveenVinayakS** [comment]
Hi @andreagemelli i have enabled "add_ewights=True" and keyerror : 'feat' is resolved but i am facing an another problem...i just getting a message "Killed"
![image](https://user-images.githubusercontent.com/27666222/207338311-c772ceba-4403-4ab6-85bf-6392613199fd.png)

**Comment by andreagemelli** [comment]
The 'feat' seems to be solved, while the last one 'killed' process I guess you may fixed it since you could get the results.
Can we close this issue?

**Comment by NaveenVinayakS** [comment]
yes @andreagemelli .
