### ISSUE TITLE
dont know where the output /prediciton is saved..

### ISSUE THREAD

**Issue by NaveenVinayakS** [andreagemelli/doc2graph#5]
python src/main.py -addG -addT -addE -addV --gpu 0 --test --weights e2e-funsd-best.pt

using this command i got BEST and AVERAGE results for the model , but i dont know where the output/prediciton is saved..

**Comment by andreagemelli** [comment]
Numerical outputs can be found where the models are tested, in `training/funsd.py` and `training/pau.py` respectively.
Then, you can use the information along with the`print_graph()` utility in `data/dataloader.py`.
Every method is commented and described, should be straighforward do what you are asking for.

Adding automatically this utility is in my todo list.
