### ISSUE TITLE
Training on DocVQA?

### ISSUE THREAD

**Issue by logan-markewich** [andreagemelli/doc2graph#9]
Super interesting project you have here!

I'm interested in training for DocVQA. I've used models like LiLT and LayoutLMV1/2/3 in the past, but graph approaches like this are pretty new to me.

Traditionally, DocVQA models are setup to predict start/end positions of the answer within the input text. Any tips on setting this up with Doc2Graph?

**Comment by andreagemelli** [comment]
It is a great idea! Actually I am kind of working on it as well: I think we can use Doc2Graph as an encoder, but still figuring out about decoder part 😜

**Comment by logan-markewich** [comment]
Sounds good! I will take some time to read the code more and let you know if I come up with anything that works 👍

**Comment by andreagemelli** [comment]
Looking forward for your progress! 
Feel free to reopen this issue when you have news or directly text me!

**Comment by andreagemelli** [comment]
Looking forward for your progress! 
Feel free to reopen this issue when you have news or directly text me!

**Comment by logan-markewich** [comment]
Just some more thoughts on this:

We could use the existing E2E graph model, with just a few minor tweaks:
- use edges as learnable features only, no classes
- predicting the class of node should uses some kind of aggregate of all that node's edges? (unsure on this one)
- when predicting the class of a node, there are only three possible classes (start, end, none)
- the predicted start/end nodes are matched back ground truth start/end nodes, and loss is calculated
- (optional) use a learnable? roberta/bert embedding model to convert initial graph into features instead of spacy

Not totally sure how to implement this just yet, but I think I'll try to figure it out this week
